# Generated by Django 6.0.6 on 2026-07-14 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_isbn', message='ISBN must be exactly 13 digits.', regex='^\\d{13}$')]),
        ),
    ]
