# Generated by Django 6.0.6 on 2026-07-14 16:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_fine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['-request_date']},
        ),
        migrations.AddField(
            model_name='borrow',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_borrowings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrow',
            name='rejected_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='borrow',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Request'), ('BORROWED', 'Borrowed'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
