# Generated by Django 5.2.3 on 2026-07-15 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='OnlineLib', max_length=100)),
                ('site_description', models.TextField(blank=True, default='Smart Library Management System')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('default_loan_days', models.PositiveIntegerField(default=14, help_text='Default loan period for books (days)')),
                ('max_loan_days', models.PositiveIntegerField(default=30, help_text='Maximum loan period (days)')),
                ('max_books_per_user', models.PositiveIntegerField(default=5, help_text='Maximum number of books a user can borrow simultaneously')),
                ('allow_auto_renew', models.BooleanField(default=False, help_text='Enable automatic loan renewal')),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=1.0, help_text='Fine amount per day overdue (USD)', max_digits=6)),
                ('max_fine_amount', models.DecimalField(decimal_places=2, default=50.0, help_text='Maximum fine amount per book', max_digits=8)),
                ('grace_period_days', models.PositiveIntegerField(default=0, help_text='Number of grace days before fines are applied')),
                ('reservation_expiry_days', models.PositiveIntegerField(default=3, help_text='Reservation validity period after availability notification (days)')),
                ('max_reservations_per_user', models.PositiveIntegerField(default=3, help_text='Maximum concurrent reservations per user')),
                ('enable_email_notifications', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('enable_sms_notifications', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('due_reminder_days', models.PositiveIntegerField(default=3, help_text='Days before due date to send reminders')),
                ('require_email_verification', models.BooleanField(default=True, help_text='Require email verification for registration')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60, help_text='Session timeout duration (minutes)')),
                ('max_login_attempts', models.PositiveIntegerField(default=5, help_text='Maximum failed login attempts')),
                ('primary_color', models.CharField(default='#6366f1', help_text='Primary site color (HEX)', max_length=7)),
                ('secondary_color', models.CharField(default='#10b981', help_text='Secondary site color (HEX)', max_length=7)),
                ('show_hero_section', models.BooleanField(default=True, help_text='Show hero section on home page')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Library Settings',
                'verbose_name_plural': 'Library Settings',
            },
        ),
    ]
